# Generated by Django 4.2.1 on 2023-07-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='Cantidad_alumno',
            field=models.IntegerField(null=True),
        ),
    ]
